### PR TITLE
fix(skymp5-functions-lib): reset round when all players have left

### LINKED ISSUE #682: When everyone gets out of the round - stop it

### PR DESCRIPTION
**Pull request by nic11**
closes #682

### CODE REVIEW

File: skymp5-functions-lib/src/sweetPie.ts [hunk 1]
```diff
@@ -180,9 +184,13 @@ export class SweetPieGameModeListener implements GameModeListener {
         }
       }
     } else if (dialogId === this.leaveRoundConfirmationDialog[0]) {
+      const roundIndex = getPlayerCurrentRoundIndex(this.rounds, actorId);
```
Comment (Pospelove) [inline skymp5-functions-lib/src/sweetPie.ts:187]: maybe better `thid.rounds.indexOf(getPlayerCurrentRound)` to not to create extra function

**Review by Pospelove — CHANGES_REQUESTED** [review]

**Review by Pospelove — APPROVED** [review]
