### PR TITLE
fix: implement low level SetInventory to avoid CTDs on mass inventory operations

### LINKED ISSUE #1115: [Bug]: Actor.unequipItemEx / Actor.unequipSpell causes freeze
### Severity

Major. A crucial error that indicates a deviation from business logic or disrupts the program, but doesn't have a vital impact on the app.

### Priority

Medium. Anything that negatively affects the user experience.

### Description

This issue similar to https://github.com/skyrim-multiplayer/skymp/issues/706.

1. When you call Actor.unequipItemEx for player when player is attacking, the game freezes.
2. When you call Actor.unequipSpell for player when spell is drawn, the game freezes.

### OS

Windows

### OS version

10

### Skyrim version

1.5.97.0.8

### SKSE version

2.0.20

### client commit''s hash

7b58795532d00ccec53e4bd157e578144686fd56

### server commit''s hash

NA

### Videocard model

GTX1070

### Steps to reproduce

See Description.

### Expected result

Player unequip Item/Spell safely.

### Actual result

The game freezes.

### LINKED ISSUE #1318: Fix crash when 10+ people with equipped items arrive
# Task

We need to add a native `applyInventory` function instead of TS-written `applyInventory` that uses `AddItemEx`

- in `InventoryApi.cpp` add `ApplyInventory` method that accepts a formId and an object of type `Inventory` as parameters.
- move `Extra`, `BasicEntry`, `Entry` and `Inventory` types from `inventory.ts` to `skyrimPlatform.ts` (it's needed to use `Inventory` type in function declaration)
- Implement ApplyInventory like this https://github.com/tiltedphoques/TiltedEvolution/blob/master/Code/client/Games/Skyrim/TESObjectREFR.cpp#L445
- Use new native function here instead of TS-written one:
https://github.com/skyrim-multiplayer/skymp/blob/be5ee043dda83fc057c954fe9ca07ca4e10fb764/skymp5-client/src/sync/equipment.ts#L29

# How to test

1. equipment (armor, shield, torch, weapons) should keep working (we can test locally with our clone)
2. ask SupAidme to re-test crashes with real players

# Additional context

There is an `AddItemEx` function that is used for adding/removing/equipping/unequipping items including items with extra data like enchantment, poison (in theory)

https://github.com/skyrim-multiplayer/skymp/blob/f8ecd0b2d45aaa84373ba04e4324e683d2176f1c/skyrim-platform/src/platform_se/skyrim_platform/PapyrusTESModPlatform.cpp#L503

We want to get rid of this function at some point cause it's a bit ugly, **it also sometimes crashes the game for some reason.**

Original report by SUPAIDME:

> 1. Народ вылетает в одной ячейке при 10+ (если все голые то никто не вылетает - мистика)
Если изначально ты в пустой (без актеров) ячейке или с парой актеров (до 10) и  еще 10 человек по 2 по 3 приходят, то вплоть до 20-25 (в зависимости от мощности пк) ты можешь с ними стоять и не вылетать. Если же зайти в ячейку где сразу много актеров, тогда уже вылетит.

### PR DESCRIPTION
**Pull request by che6a**
closes #1318
closes #1115

### CODE REVIEW

File: skyrim-platform/src/platform_se/codegen/convert-files/skyrimPlatform.ts [hunk 1]
```diff
@@ -1543,6 +1543,33 @@ export declare function getNumCreatedTexts(): number;
...
+}
+
+export type Entry = BasicEntry & Extra;
+
+export interface Inventory {
+  entries: Entry[];
+}
+
+export declare function setInventory(formId: number, inventory: Inventory): void;
+
```
Comment (Wedmer) [inline skyrim-platform/src/platform_se/codegen/convert-files/skyrimPlatform.ts:1572]: Looks like you have manually added this. AFAIK it should be generated.

**Review by Wedmer — CHANGES_REQUESTED** [review]
Somehow it has broken some post build steps for linux build.

**Comment by Pospelove** [comment]
https://github.com/tiltedphoques/TiltedEvolution/blob/master/Code/client/Games/Skyrim/TESObjectREFR.cpp#L488

File: skyrim-platform/src/platform_se/skyrim_platform/InventoryApi.cpp [hunk 2]
```diff
@@ -209,3 +212,65 @@ JsValue InventoryApi::GetContainer(const JsFunctionArguments& args)
...
+    const bool worn =
+      entry.GetProperty("worn").GetType() != JsValue::Type::Undefined
+      ? static_cast<bool>(entry.GetProperty("worn"))
+      : false;
+    const bool wornLeft =
+      entry.GetProperty("wornLeft").GetType() != JsValue::Type::Undefined
+      ? static_cast<bool>(entry.GetProperty("wornLeft"))
+      : false;
+    g_nativeCallRequirements.gameThrQ->AddTask(
+      [pActor, pBoundObject, count]() {
```
Comment (Pospelove) [inline skyrim-platform/src/platform_se/skyrim_platform/InventoryApi.cpp:243]: pActor and pBoundObject may invalidate right before the task will be executed

File: skyrim-platform/src/platform_se/skyrim_platform/InventoryApi.cpp [hunk 3]
```diff
@@ -209,3 +212,65 @@ JsValue InventoryApi::GetContainer(const JsFunctionArguments& args)
...
+      RightHand = 0x13f42
+    };
+    if (worn || wornLeft) {
+      RE::BGSEquipSlot* slot = worn
+        ? static_cast<RE::BGSEquipSlot*>(
+            RE::TESForm::LookupByID(EquipSlot::RightHand))
+        : static_cast<RE::BGSEquipSlot*>(
+            RE::TESForm::LookupByID(EquipSlot::LeftHand));
+      g_nativeCallRequirements.gameThrQ->AddTask(
+        [equipManager, pActor, pBoundObject, slot]() {
```
Comment (Pospelove) [inline skyrim-platform/src/platform_se/skyrim_platform/InventoryApi.cpp:261]: same

**Review by Pospelove — CHANGES_REQUESTED** [review]

File: skyrim-platform/src/platform_se/skyrim_platform/InventoryApi.cpp [hunk 4]
```diff
@@ -239,12 +230,18 @@ JsValue InventoryApi::SetInventory(const JsFunctionArguments& args)
       entry.GetProperty("wornLeft").GetType() != JsValue::Type::Undefined
       ? static_cast<bool>(entry.GetProperty("wornLeft"))
       : false;
-    g_nativeCallRequirements.gameThrQ->AddTask(
-      [pActor, pBoundObject, count]() {
-        pActor->AddObjectToContainer(pBoundObject, nullptr, count, nullptr);
-      });
-    RE::ActorEquipManager* equipManager =
-      RE::ActorEquipManager::GetSingleton();
+    g_nativeCallRequirements.gameThrQ->AddTask([formId, baseId, count]() {
```
Comment (Pospelove) [inline skyrim-platform/src/platform_se/skyrim_platform/InventoryApi.cpp:233]: That's correct

But I think it'd be reasonable to throw exceptions outside of the tasks.

Otherwise, we will not be able to receive this exception on the typescript side (the function would finish successfully, adding a throwing task instead of failing itself)

Let's double-check:
1. throw exceptions in the function itself (not the task)
2. in case of check fails inside a task - do nothing

**Review by Pospelove — CHANGES_REQUESTED** [review]

File: skyrim-platform/src/platform_se/skyrim_platform/InventoryApi.cpp [hunk 5]
```diff
@@ -209,3 +212,72 @@ JsValue InventoryApi::GetContainer(const JsFunctionArguments& args)
...
+      : false;
+    g_nativeCallRequirements.gameThrQ->AddTask([formId, baseId, count]() {
+      RE::Actor* pActor = RE::TESForm::LookupByID<RE::Actor>(formId);
+      if (!pActor) {
+        throw NullPointerException("pActor");
+      }
+      RE::TESBoundObject* pBoundObject =
+        RE::TESForm::LookupByID<RE::TESBoundObject>(baseId);
+      if (!pBoundObject) {
+        throw NullPointerException("pBoundObject");
```
Comment (Pospelove) [inline skyrim-platform/src/platform_se/skyrim_platform/InventoryApi.cpp:241]: continue; + add todo comment

File: skyrim-platform/src/platform_se/skyrim_platform/InventoryApi.cpp [hunk 6]
```diff
@@ -209,3 +212,81 @@ JsValue InventoryApi::GetContainer(const JsFunctionArguments& args)
...
+      LeftHand = 0x13f43,
+      RightHand = 0x13f42
+    };
+    if (worn || wornLeft) {
+      RE::BGSEquipSlot* slot = worn
+        ? static_cast<RE::BGSEquipSlot*>(
+            RE::TESForm::LookupByID(EquipSlot::RightHand))
+        : static_cast<RE::BGSEquipSlot*>(
+            RE::TESForm::LookupByID(EquipSlot::LeftHand));
+      g_nativeCallRequirements.gameThrQ->AddTask([formId, baseId, slot]() {
```
Comment (Pospelove) [inline skyrim-platform/src/platform_se/skyrim_platform/InventoryApi.cpp:266]: let's do only one AddTask per SetInventory

**Review by Pospelove — APPROVED** [review]

**Review by Wedmer — APPROVED** [review]

**Comment by Pospelove** [comment]
TODO: merge once CI is green
