### PR TITLE
fix(skymp5-front): rewrite ImageButton, SkyrimButton to TypeScript, fix interfaces for other buttons

### LINKED ISSUE #473: Rewrite SkyrimButton to TS

### PR DESCRIPTION
**Pull request by vladdenisov**
Closes #473, #472

### CODE REVIEW

File: skymp5-front/src/components/SkyrimButton/index.tsx [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+            style={{ width: `${width}px`, height: `${height}px`, opacity: disabled ? 0.6 : 1.0 }}
+            className={'skymp-input-button'}
+            onClick={(e) => onClick && !disabled ? onClick(e) : console.log(e)}
+        >
+            <span className={'skymp-input-button_text'} style={{ maxHeight: `${height}px` }}>{text}</span>
+        </div>
+  );
+};
+
+export default SkyrimButton;
```
Comment (JustCaptcha) [inline skymp5-front/src/components/SkyrimButton/index.tsx:18]: Let's use named exports everywhere.

File: skymp5-front/src/interfaces/buttons.ts [hunk 2]
```diff
@@ -1,16 +1,33 @@
...
     onClick?: (any?: any) => void;
 }
+
+export interface ImageButtonProps extends DefaultButtonComponentProps{
+    src: string
+}
+
+export interface SkyrimButtonProps extends DefaultButtonComponentProps {
+    text: string
+}
```
Comment (JustCaptcha) [inline skymp5-front/src/interfaces/buttons.ts:22]: Add empty line.

File: skymp5-front/src/components/SkyrimButton/index.tsx [hunk 3]
```diff
@@ -0,0 +1,18 @@
+import React from 'react';
+
+import './styles.scss';
```
Comment (JustCaptcha) [inline skymp5-front/src/components/SkyrimButton/index.tsx:3]: `index.tsx` and `style.scss` becomes `SkyrimButton.tsx` and `SkyrimButton.scss` accordingly.

**Review by JustCaptcha — CHANGES_REQUESTED** [review]

File: skymp5-front/src/components/ImageButton/index.tsx [hunk 4]
```diff
@@ -0,0 +1,18 @@
...
+          onClick={(e) => onClick && !disabled ? onClick(e) : console.log(e)}
+          className={'login-form--content_social__link'}
+          style={{ opacity: disabled ? 0.6 : 1.0, cursor: disabled ? 'default' : 'pointer' }}
+      >
+        <img src={src} />
+      </div>
+  );
+};
+
+export default ImageButton;
```
Comment (JustCaptcha) [inline skymp5-front/src/components/ImageButton/index.tsx:18]: Let's use named exports everywhere.

File: skymp5-front/src/components/ImageButton/index.tsx [hunk 5]
```diff
@@ -0,0 +1,18 @@
+import React from 'react';
+
+import '../../features/login/styles.scss';
```
Comment (JustCaptcha) [inline skymp5-front/src/components/ImageButton/index.tsx:3]: Change filenames.

**Review by JustCaptcha — CHANGES_REQUESTED** [review]

File: skymp5-front/src/components/FrameButton/index.tsx [hunk 6]
```diff
@@ -1,69 +1,59 @@
 import React from 'react';
-import { IDefaultUIComponentProps } from '../../interfaces';
+import { ButtonItemProps, FrameButtonProps } from '../../interfaces';
 import './styles.scss';
 
-interface IFrameButtonProps extends IDefaultUIComponentProps {
-    variant: string;
-}
+const ButtonItem = (props: ButtonItemProps) => {
```
Comment (JustCaptcha) [inline skymp5-front/src/components/FrameButton/index.tsx:5]: Let's destructure props.

File: skymp5-front/src/interfaces/buttons.ts [hunk 7]
```diff
@@ -1,16 +1,34 @@
...
+
+export interface FrameButtonProps extends DefaultButtonComponentProps {
+    variant: string;
+    text: string;
+}
+
+export interface ButtonItemProps extends DefaultButtonComponentProps {
+    name: string;
+    text?: string;
```
Comment (JustCaptcha) [inline skymp5-front/src/interfaces/buttons.ts:31]: ButtonItemProps shouldn't be here. It's too specific and fractional.

**Review by JustCaptcha — CHANGES_REQUESTED** [review]

**Review by JustCaptcha — APPROVED** [review]
