### PR TITLE
fix(skymp5-front): fix keys and chat

### LINKED ISSUE #355: Fix "key" prop warnings
Warning: Each child in a list should have a unique "key" prop.

### PR DESCRIPTION
**Pull request by q1000treadz**
close #355 #487

### CODE REVIEW

File: skymp5-front/src/constructor.js [hunk 1]
```diff
@@ -90,11 +90,12 @@ const Constructor = props => {
...
       const [hints, setHints] = useState(hintsarr);
       let hintIndex = 0;
-      bodylines.forEach((line) => {
+      bodylines.forEach((line, lineIndex) => {
         let arr = [];
-        line.forEach((obj) => {
+        line.forEach((obj, elementIndex) => {
           let curElem = undefined;
           let hasHint = obj.element.hint != undefined ? true : false;
+          let key = lineIndex + elementIndex + obj.element.type;
```
Comment (Pospelove) [inline skymp5-front/src/constructor.js:98]: There will be collisions. Maybe something like lineIndex + "_" + elementIndex + "_" + obj.element.type?

**Review by Pospelove — CHANGES_REQUESTED** [review]

File: skymp5-front/src/constructor.js [hunk 2]
```diff
@@ -131,19 +132,19 @@ const Constructor = props => {
...
                     {curElem}
-                  </>
+                  </div>
                 )
             );
             if (hasHint) hintIndex++;
           }
         });
-        result.body.push(<div className={'container'}>{arr}</div>);
+        result.body.push(<div key={lineIndex + "constainer"} className={'container'}>{arr}</div>);
```
Comment (Pospelove) [inline skymp5-front/src/constructor.js:147]: constainer -> container

**Review by Pospelove — APPROVED** [review]
