### PR TITLE
fix(skyrim-platform): change behavior of cursor render

### LINKED ISSUE #506: Apply cursor revert only when browser is visible
SP currently reverts cursor to vanilla. But it's a fake cursor.

Disable rendering of original SWF:
https://github.com/skyrim-multiplayer/skymp/blob/bf88abcc1922bbbfc12e177e522453f95eb60113/skyrim-platform/src/platform_se/skyrim_platform/FridaHooks.cpp#L275

Render it again:
https://github.com/skyrim-multiplayer/skymp/blob/main/skyrim-platform/src/tilted/ui/DX11RenderHandler.cpp#L66

**Chromium draws after SWF menus. But we need to draw a cursor after Chromium. But some users do not want Chrome at all, they need their modded custom cursors back** 

since drawing this ill-fated cursor is necessary for the browser, I would do it like this. if the browser is visible then draw our png cursor
if not visible then the original cursor
original in terms of SWF

### PR DESCRIPTION
**Pull request by shevernitskiy**
closes #506 

This little patch changes the behaviour of rendering custom png cursor.

Before: sp redraws cursor with custom all the time
After: cursor swtiched to png only in case of browser focused and visible

The reason why we need this two flags is that people can use broswer in "widget" mode.

### CODE REVIEW

File: skyrim-platform/src/platform_se/skyrim_platform/FridaHooks.cpp [hunk 1]
```diff
@@ -25,6 +25,9 @@
 #include <sstream>
 #include <windows.h>
 
+#include <hooks/DInputHook.hpp>
```
Comment (Pospelove) [inline skyrim-platform/src/platform_se/skyrim_platform/FridaHooks.cpp:28]: we include our (non-library) files with "" syntax (not <>)
and also please remove whitespace at line 27

File: skyrim-platform/src/platform_se/skyrim_platform/FridaHooks.cpp [hunk 2]
```diff
@@ -110,9 +113,10 @@ void SetupFridaHooks()
 }
 
 thread_local uint32_t g_queueNiNodeActorId = 0;
-thread_local void* g_prevMainMenuView = nullptr;
+thread_local void* g_prevMainCursorView = nullptr;
```
Comment (Pospelove) [inline skyrim-platform/src/platform_se/skyrim_platform/FridaHooks.cpp:116]: CursorMenu, not MainCursor

**Review by Pospelove — CHANGES_REQUESTED** [review]
review: part 1

File: skyrim-platform/src/platform_se/skyrim_platform/FridaHooks.cpp [hunk 3]
```diff
@@ -318,16 +336,16 @@ static void example_listener_on_leave(GumInvocationListener* listener,
     case RENDER_MAIN_MENU: {
```
Comment (Pospelove) [inline skyrim-platform/src/platform_se/skyrim_platform/FridaHooks.cpp:336]: case RENDER_CURSOR_MENU: {

**Review by Pospelove — CHANGES_REQUESTED** [review]
g_prevCursorMenuView and g_prevMemorizedCursorMenuView do exactly same, please leave only one

File: skyrim-platform/src/platform_se/skyrim_platform/FridaHooksUtils.cpp [hunk 4]
```diff
@@ -11,3 +11,16 @@ void* FridaHooksUtils::GetMenuByName(void* name)
   }
   return nullptr;
 }
+
+void FridaHooksUtils::SetMenuNumberVariable(void* name, const char* target,
+                                            double value)
+{
+  if (auto mm = MenuManager::GetSingleton()) {
+    auto view = mm->GetMovieView((BSFixedString*)name);
```
Comment (Pospelove) [inline skyrim-platform/src/platform_se/skyrim_platform/FridaHooksUtils.cpp:19]: (BSFixedString*)name -> reinterpret_cast<BSFixedString *>(name);
name -> fsName (fixed string)

**Review by Pospelove — CHANGES_REQUESTED** [review]

**Review by Pospelove — APPROVED** [review]
