### PR TITLE
internal: fix Windows build with modern DirectX libs

### LINKED ISSUE #1219: GitHub Windows build broken
OK:
https://github.com/skyrim-multiplayer/skymp/actions/runs/3470903801/jobs/5806600839
Runner Image
  Image: windows-2022
  Version: 20221027.1
  Included Software: https://github.com/actions/runner-images/blob/win22/20221027.1/images/win/Windows2022-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20221027.1

NOT OK:
https://github.com/skyrim-multiplayer/skymp/actions/runs/3470903801/jobs/5799693982
Runner Image
  Image: windows-2022
  Version: 20221111.1
  Included Software: https://github.com/actions/runner-images/blob/win22/20221111.1/images/win/Windows2022-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20221111.1

### PR DESCRIPTION
**Pull request by nic11**
Fixes #1219

### CODE REVIEW

File: skyrim-platform/src/tilted/ui/DX11RenderHandler.h [hunk 1]
```diff
@@ -2,17 +2,14 @@
...
 #include <Signal.hpp>
 #include <functional>
 #include <mutex>
 #include <wrl.h>
 
-namespace DirectX {
-class SpriteBatch;
-class CommonStates;
-class SpriteFont;
-}
```
Comment (nic11) [inline skyrim-platform/src/tilted/ui/DX11RenderHandler.h:14]: `inline namespace DX11` appeared which came into conflict with this fwd declaration. Probably could also be fixed by adding it into this fwd declaration, but this would probably break older stuff...

Anyway, this file isn't included from anywhere else, so no much sense in making fwd declarations here

**Comment by Pospelove** [comment]
@nic11 Holy shi* I love that, good job
