### PR TITLE
fix(skymp5-server): fix incorrect attack range

### LINKED ISSUE #425: [Bug]: Incorrect dagger attack range
### Severity

Major. A crucial error that indicates a deviation from business logic or disrupts the program, but doesn't have a vital impact on the app.

### Priority

Medium. Anything that negatively affects the user experience.

### Description

There is no correct attack distance in the game. This is especially evident on weapons with a small range. It is possible that the size of the players' bodies is not used in calculating the distance. When attacking with a dagger, the server deals damage from a shorter distance than it should be.

i think we need change range attack for knife and probably to other weapon(we testing it)

### OS

Windows

### OS version

11

### Skyrim version

1.5.97.0.8

### SKSE version

2.0.20

### client commit''s hash

f48b9dab95835d5133e86d00a5859545f0c5cc9a

### server commit''s hash

f48b9dab95835d5133e86d00a5859545f0c5cc9a

### Videocard model

AMD RX 

### Steps to reproduce

1. take knife
2. attack player 2 at the border of the distance where the hit effect begins to be displayed
3. Server dont give any damage
4. Step towards player 2 and attack again
5. If the server does not deal damage to player 2, repeat the previous step
6. as soon as the server deals damage to player 2, this will be the server weapon range

### Expected result

Server's weapon range is equal to weapon range in game

### Actual result

Server's weapon range is not equal to weapon range in game

### PR DESCRIPTION
**Pull request by Dinakrab**
close #425

### CODE REVIEW

File: skymp5-server/cpp/server_guest_lib/ActionListener.cpp [hunk 1]
```diff
@@ -545,10 +545,52 @@ float GetReach(const MpActor& actor, const uint32_t source)
   return weaponReach * fCombatDistance;
 }
 
+float GetSqrDistance(const MpActor& actor, const MpActor& target)
```
Comment (Pospelove) [inline skymp5-server/cpp/server_guest_lib/ActionListener.cpp:548]: Please rename function to make clear that object bounds are taken into account

**Review by Pospelove — CHANGES_REQUESTED** [review]

File: skymp5-server/cpp/server_guest_lib/ActionListener.cpp [hunk 2]
```diff
@@ -540,15 +535,71 @@ float GetReach(const MpActor& actor, const uint32_t source)
...
 }
 
+enum class AngleType
+{
+  Radians = 0,
+  Degrees = 1
+};
+
+template <AngleType type>
+NiPoint3 RotateZ(NiPoint3 point, float _angle)
```
Comment (Pospelove) [inline skymp5-server/cpp/server_guest_lib/ActionListener.cpp:552]: Please remove AngleType template parameter as it is never used

File: skymp5-server/cpp/server_guest_lib/ActionListener.cpp [hunk 3]
```diff
@@ -540,15 +535,71 @@ float GetReach(const MpActor& actor, const uint32_t source)
...
+{
+  static const float g_pi = std::acos(-1.f);
```
Comment (Pospelove) [inline skymp5-server/cpp/server_guest_lib/ActionListener.cpp:554]: g_pi -> kPi
g_angleToRadians -> kAngleToRadians

**Review by Pospelove — CHANGES_REQUESTED** [review]

**Comment by Pospelove** [comment]
@SupAidmi Testing required

File: skymp5-server/cpp/server_guest_lib/ActionListener.cpp [hunk 4]
```diff
@@ -540,15 +535,64 @@ float GetReach(const MpActor& actor, const uint32_t source)
...
   auto weapDNAM = espm::GetData<espm::WEAP>(source, espmProvider).weapDNAM;
-  float fCombatDistance = GetGlobalCombatDistance(espmProvider);
+  float fCombatDistance =
+    espm::GetData<espm::GMST>(espm::GMST::kFCombatDistance, espmProvider)
+      .value;
   float weaponReach = weapDNAM ? weapDNAM->reach : 0;
   return weaponReach * fCombatDistance;
 }
 
+NiPoint3 RotateZ(NiPoint3 point, float _angle)
```
Comment (Pospelove) [inline skymp5-server/cpp/server_guest_lib/ActionListener.cpp:545]: Bad naming `float _angle`

**Review by Pospelove — CHANGES_REQUESTED** [review]

File: skymp5-server/cpp/server_guest_lib/ActionListener.cpp (hunk 4 above)
Comment (Pospelove) [reply skymp5-server/cpp/server_guest_lib/ActionListener.cpp:545]: const NiPoint3 &point

**Comment by Pospelove** [comment]
@Dinakrab  there is a small distance that isn't covered. please add multiplier or modifier to fix (discussed in Discord yesterday)

**Review by Pospelove — APPROVED** [review]

**Review by Pospelove — APPROVED** [review]
